Repository andela/forsetti-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#36 #164798924 Users should be able to report an article
  package-lock.json
  server/controllers/index.js
  server/controllers/report.controller.js
  server/migrations/20190409120010-create-report-type.js
  server/migrations/20190409120040-create-report.js
  server/models/report.js
  server/models/reporttype.js
  server/models/user.js
  server/routes/index.js
  server/routes/report.routes.js
  server/seeders/report-types.js
  server/test/report.spec.js
  server/test/stubs/mock-data.report.js
  server/utils/articles/article.util.js
  server/utils/index.js
  server/utils/reports/report.util.js
  swagger.yml
Labels: PR; Review

#34 #165210747 Implement feature get all articles
  server/controllers/article.controller.js
  server/controllers/comment.controller.js
  server/migrations/20190325190307-create-article.js
  server/migrations/20190404145044-create-comments.js
  server/models/article.js
  server/routes/article.routes.js
  server/test/article.spec.js
  server/test/ratings.spec.js
  server/utils/notifications/comment-mail.util.js
Labels: PR; Review

#33 #164798925 like a comment
  package-lock.json
  package.json
  server/controllers/comment.controller.js
  server/migrations/20190409085119-create-commentlike.js
  server/models/commentlikes.js
  server/models/comments.js
  server/models/user.js
  server/routes/article.routes.js
  server/test/commentlike.spec.js
  server/utils/comments/check-comment-like.util.js
  server/utils/index.js
  swagger.yml
Labels: Feedback Implemented, PR; Review, merge conflicts resolved

#41 #165250363 User should be able to get all report categories
  server/controllers/index.js
  server/controllers/report-category.controller.js
  server/models/report-type.js
  server/routes/report.routes.js
  server/seeders/report-types.js
  server/test/report.spec.js
Labels: Feedback Implemented, PR; Review, merge conflicts resolved

#35 #164798917 Users should be able edit tags and articles
  package-lock.json
  server/controllers/article.controller.js
  server/migrations/20190325190307-create-article.js
  server/migrations/20190409173057-create-tags.js
  server/migrations/20190409173213-create-articletag.js
  server/models/article.js
  server/models/articletag.js
  server/models/tag.js
  server/routes/article.routes.js
  server/seeders/20190407220433-articles.js
  server/seeders/20190409174404-tag.js
  server/seeders/20190409174415-articletags.js
  server/test/article.spec.js
  server/test/stubs/mock-data.article.js
  server/utils/articles/article.util.js
  server/utils/index.js
  swagger.yml
Labels: Feedback Implemented, PR; Review

#37 #164798915 User can follow and unfollow
  server/controllers/profile.controller.js
  server/routes/index.js
  server/routes/profile.routes.js
  server/routes/users.routes.js
  server/seeders/20190404111305-users.js
  server/test/follow.spec.js
  server/test/user.spec.js
  swagger.yml
Labels: Feedback Implemented, PR; Review

#44 165310592 Set up Github Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR; Review

#47 #164798922 Implement article share via mail functionality
  server/controllers/article.controller.js
  server/routes/article.routes.js
  server/test/article.spec.js
  server/test/stubs/mock-data.share.js
  server/utils/articles/article.util.js
  server/utils/index.js
  swagger.yml
Labels: PR; Review

#38 #164798928 user highlight article
  server/controllers/comment.controller.js
  server/migrations/20190404145044-create-comments.js
  server/migrations/20190407044853-create-clap.js
  server/models/comments.js
  server/routes/article.routes.js
  server/test/comment.spec.js
  server/utils/articles/highlightvalidate.util.js
  server/utils/index.js
Labels: PR; Review

#45 #164798919 Users should be able to see existing authors profile
  server/controllers/user.controller.js
  server/routes/users.routes.js
  server/test/user.spec.js
  swagger.yml
Labels: merge conflicts resolved

#46 #164798918 implement pagination feature
  package-lock.json
  package.json
  server/controllers/article.controller.js
  server/routes/article.routes.js
  server/test/article.spec.js
  server/utils/articles/article.util.js
  server/utils/articles/base.util.js
  server/utils/index.js
  swagger.yml
Labels: PR; Review

#49 #164798920 create search route
  server/controllers/article-search-controller.js
  server/controllers/index.js
  server/routes/article.routes.js
  server/test/article-search.spec.js
  server/utils/articles/article-search.utils.js
  server/utils/index.js
  swagger.yml
Labels: Feedback Implemented, merge conflicts resolved

#51 #165343963 delete an article
  app.json
  server/controllers/article.controller.js
  server/models/article.js
  server/routes/article.routes.js
  server/seeders/20190407220433-articles.js
  server/test/article.spec.js
  server/utils/articles/article.util.js
  server/utils/articles/deleteImage.util.js
  server/utils/index.js
  swagger.yml
Labels: Feedback Implemented, merge conflicts resolved

#52 #165344022 implement get user notifications functionality
  server/controllers/profile.controller.js
  server/models/notification.js
  server/routes/profile.routes.js
  server/test/user.spec.js
  swagger.yml
Labels: PR; Review, merge conflicts resolved

#54 165383342 Fix Login validations
  server/controllers/user.controller.js
  server/routes/auth.routes.js
  server/seeders/20190404111305-users.js
  server/test/article.spec.js
  server/test/bookmark.spec.js
  server/test/clap.spec.js
  server/test/comment.spec.js
  server/test/commentlike.spec.js
  server/test/follow.spec.js
  server/test/report.spec.js
  server/test/signup.spec.js
  server/test/stubs/mock-data.user.js
  server/test/user-login.spec.js
  server/test/user.spec.js
  server/utils/index.js
  server/utils/users/user.util.js
Labels: bug, merge conflicts resolved

#56 #164798929 User should be able to track comment edit history
  server/controllers/comment.controller.js
  server/migrations/20190416104305-create-comment-history.js
  server/models/comment-history.js
  server/routes/article.routes.js
  server/seeders/20190416094115-comments.js
  server/seeders/20190416140323-comment-history.js
  server/test/comment.spec.js
  server/utils/commentidvalidator.util.js
  server/utils/comments/comment-history.util.js
  server/utils/index.js
  swagger.yml
Labels: PR; Review, merge conflicts resolved

#57 #165344059 implement edit comment feature
  server/controllers/comment.controller.js
  server/routes/article.routes.js
  server/seeders/20190417093125-comments.js
  server/test/comment.spec.js
  server/utils/comments/comments.util.js
  server/utils/index.js
  swagger.yml
Labels: PR: Ready

#58 #165343781 user view followers and followee
  server/controllers/profile.controller.js
  server/controllers/user.controller.js
  server/models/user.js
  server/routes/profile.routes.js
  server/seeders/20190404111308-followers.js
  server/test/follow.spec.js
  swagger.yml
Labels: PR; Review, merge conflicts resolved

#62 #165390743 Implement email notification functions in necessary routes.
  server/controllers/article.controller.js
  server/controllers/comment.controller.js
  server/controllers/profile.controller.js
  server/migrations/20190404082058-create-notification.js
  server/models/notification.js
  server/test/notification.spec.js
  server/utils/notifications/article-mail.util.js
  server/utils/notifications/comment-mail.util.js
  server/utils/notifications/follows-mail.util.js
Labels: bug fix

#60 #165383031 get all tags
  package-lock.json
  server/controllers/article.controller.js
  server/routes/article.routes.js
  server/test/article.spec.js
  swagger.yml
Labels: merge conflicts resolved

#61 #165382909 Users should be able to get top rated articles
  package-lock.json
  server/controllers/article.controller.js
  server/models/article.js
  server/models/clap.js
  server/routes/article.routes.js
  server/seeders/20190407220433-articles.js
  server/test/article.spec.js
  server/test/stubs/mock-data.article.js
  server/utils/articles/article.util.js
  server/utils/articles/base.util.js
  server/utils/rating.util.js
  swagger.yml
Labels: PR; Review
